if(DEFINED ENV{ALTBASE_XWIN_SDK})
  set(ALTBASE_XWIN_SDK "$ENV{ALTBASE_XWIN_SDK}")
else()
  set(ALTBASE_XWIN_SDK "$ENV{HOME}/.cache/altbase-build/xwin-sdk")
endif()
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_C_COMPILER clang-cl-19)
set(CMAKE_CXX_COMPILER clang-cl-19)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_LINKER lld-link-19)
set(CMAKE_AR llvm-lib-19)
set(CMAKE_RC_COMPILER llvm-rc-19)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
set(CMAKE_C_FLAGS_INIT "/imsvc${ALTBASE_XWIN_SDK}/crt/include /imsvc${ALTBASE_XWIN_SDK}/sdk/include/ucrt /imsvc${ALTBASE_XWIN_SDK}/sdk/include/shared /imsvc${ALTBASE_XWIN_SDK}/sdk/include/um")
set(CMAKE_CXX_FLAGS_INIT "/imsvc${ALTBASE_XWIN_SDK}/crt/include /imsvc${ALTBASE_XWIN_SDK}/sdk/include/ucrt /imsvc${ALTBASE_XWIN_SDK}/sdk/include/shared /imsvc${ALTBASE_XWIN_SDK}/sdk/include/um")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/libpath:${ALTBASE_XWIN_SDK}/crt/lib/x86_64 /libpath:${ALTBASE_XWIN_SDK}/sdk/lib/ucrt/x86_64 /libpath:${ALTBASE_XWIN_SDK}/sdk/lib/um/x86_64")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "/libpath:${ALTBASE_XWIN_SDK}/crt/lib/x86_64 /libpath:${ALTBASE_XWIN_SDK}/sdk/lib/ucrt/x86_64 /libpath:${ALTBASE_XWIN_SDK}/sdk/lib/um/x86_64")
