my %targets = (
  "VC-ALTBASE-LINUX64" => {
    inherit_from => [ "VC-WIN64A" ],
    build_scheme => [ "unified", "unix" ],
    perl_platform => "Unix::AltbaseCross",
    build_file => "Makefile",
    CC => $ENV{ALTBASE_WINDOWS_CC} // "clang-cl-19",
    AR => "llvm-ar-19",
    ARFLAGS => "qc",
    aroutflag => "",
    RANLIB => "llvm-ranlib-19",
    lib_cflags => "/MT /Zl",
    CFLAGS => "/nologo /O2 /W0",
    LDFLAGS => "",
  }
);
