const assert=require('node:assert/strict'),fs=require('fs'),{connect}=require('./cdp.cjs');
const out=process.env.ALTBASE_QA_OUTPUT || '/home/user/Documents/Altbase/artifacts/reconciliation-20260908/gui-fixtures';fs.mkdirSync(out,{recursive:true});
(async()=>{const c=await connect(19508);try{await c.call('Page.navigate',{url:'http://127.0.0.1:18508/tests/gui/technical/index.html?run='+Date.now()+'#/app'});await c.wait(()=>c.evaluate('Boolean(window.qa)'),'fixture');await c.wait(()=>c.evaluate('Boolean(document.querySelector("a[href*=zano]"))'),'portfolio rendered');
 const items=await c.evaluate('qa.snapshotItems()');assert.equal(items[0].addresses[0],'bitcoincashii:qq7ty96yha3waz7vsf32wastmag47k283y3jfk4q9m');
 const row=()=>c.evaluate(`document.querySelector('a[href$="/app/coin/zano"]').parentElement.innerText`);
 for(const readiness of ['syncing','error']){await c.evaluate(`qa.privacyCase('0','${readiness}')`);await c.wait(async()=>/Current balance not verified/.test(await row()),'unverified label');assert.doesNotMatch(await row(),/0 ZANO/);assert.match(await row(),/—/);await c.screenshot(out+'/privacy-zero-'+readiness+'.png')}
 await c.evaluate("qa.privacyCase('5.668','syncing')");await c.wait(async()=>/5.668 ZANO/.test(await row()),'cached positive');assert.match(await row(),/Current balance not verified/);await c.screenshot(out+'/privacy-cached-positive.png');
 await c.evaluate("qa.privacyCase('0','ready')");await c.wait(async()=>/0 ZANO/.test(await row()),'verified zero');assert.doesNotMatch(await row(),/Current balance not verified/);
 await c.evaluate("qa.setBalance('0.09996')");await c.wait(()=>c.evaluate("document.body.innerText.includes('0.09996 BCH2')"),'BCH2 fixture balance');await c.screenshot(out+'/bch2-funded-address.png');assert.equal(await c.evaluate('qa.state.sends'),0);
 await c.evaluate("qa.privacyCase('0','error');qa.go('/app/coin/zano')");await c.wait(()=>c.evaluate("document.body.innerText.includes('Current balance not verified')"),'details unverified');
 assert.doesNotMatch((await c.snapshot()).text,/0 ZANO/);await c.screenshot(out+'/privacy-details-zero-error.png');
 await c.evaluate("qa.privacyCase('5.668','syncing')");await c.wait(()=>c.evaluate("document.body.innerText.includes('5.668 ZANO')"),'details cached positive');assert.match((await c.snapshot()).text,/Current balance not verified/);await c.screenshot(out+'/privacy-details-cached-positive.png');assert.equal(await c.evaluate('qa.state.sends'),0);
 const result={passed:7,checks:['BCH2 snapshot uses cashaddr','unfinished scan hides zero','failed scan hides zero','cached positive explicitly unverified','completed scan permits verified zero','coin details hide unavailable zero','coin details flag cached positive'],signOrBroadcastCalls:0,confirmationClicks:0};fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{c.socket.close()}})().catch(e=>{console.error(e.message);process.exitCode=1})
